### ISSUE TITLE
Cannot create a new account in common voice from the invite link 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2328]
**STR:** 
1. Navigate to a challenge invite link (e.g: https://voice.allizom.org/?challenge=pilot&team=ibm&invite=7c2be817-0477-11ea-bb30-067a2205f3e0)
2. Accept terms and conditions and click "Join the IBM team" from the modal
3. Enter an email address never used before in the Common Voice
4. Click "Enter" and send login link
5. Login to your email server and click the login link from the email

**Expected:**
User is redirected to the profile page to create a common voice profile

**Actual:**
Error message is returned for a few seconds, then user is redirected to login page. Browser console shows no errors.  

![sign up to team-2019-11-14_16 32 23(1)](https://user-images.githubusercontent.com/5293100/68867639-dac49e80-06fe-11ea-94e8-71ff451fe7e5.gif)

**Note:**
Following steps 1-2, then using the google login with an account not used in common voice before returns login page with errors in browser console.
See below.
![image_2019_11_14T14_25_18_005Z](https://user-images.githubusercontent.com/5293100/68867901-41e25300-06ff-11ea-8a0d-489fa8aaf00a.png)

**Comment by phirework** [comment]
@can-007 @catherine917 I've reverted the main commits that I think could be affecting this and it's still persisting. Can you take a look at the pieces of `api.ts` that are throwing up the error and see what's up? 

This is reproducible on my local using docker, let me know if you run into issues with that. 

cc @rileyjshaw

**Comment by can-007** [comment]
I tried the allizom.org, using the linked provided above. But the allizom.org could redirect to the Profile page correctly.
I think the root cause is the same as https://github.com/mozilla/voice-web/issues/2324.

**Comment by rleitan** [comment]
The issue is still reproducible. I can see the Build profile page but when I click  Save button the error is displayed

**Comment by phirework** [comment]
Confirming that @rleitan's description of the problem is still reproducible. You have to click save on the profile page redirect to get the error.

**Comment by can-007** [comment]
That is strange.
@phirework , I have a theory that before the challenge board is loaded, the front-end sends out a request for account. The account contains user's enrollment information. And before the account is returned, challenge board is loaded, and send requests for challenge information like points, current week, etc. But these requests need the enrollment information which is not available at that time.
Thus, crashes the front-end.

**Comment by phirework** [comment]
@rleitan This should be fixed on stage! Crossing all my fingers :D

**Comment by rileyjshaw** [comment]
🤞 🤞 🤞 🤞 🤞 🤞 🤞

**Comment by phirework** [comment]
Note for @rleitan - currently this works if you're ONLY accepting the privacy policy, not if you're also signing up for the email newsletter. The email newsletter bugs are related to #2330.

**Comment by viorelaioia** [comment]
This issue is still happening on my end. 
For passwordless login, I'm getting the exact same results as in the description of this bug. 
For google login, I'm getting the results @rleitan described above .

**Comment by phirework** [comment]
Can you verify what invite link you're using? And/or try this link? http://voice.allizom.org/en?challenge=pilot&team=ibm&invited_by=762b1e65-08e1-11ea-bb30-067a2205f3e0 That's what @mbransn and I were using to test yesterday. 

One of the things we discovered during troubleshooting is that if the invited_by value is invalid, the entire thing will be rejected instead of just ignoring the invited_by value, and at this point there's been enough testing that I can't actually tell what is and isn't a correct value for that.

**Comment by viorelaioia** [comment]
@phirework , I tested this in production with an invite link that @mbransn provided and I can confirm I didn't encounter this issue.
